"""
Django settings for test_dj project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# 1. 项目基础路径 & 环境变量加载
# 项目根目录（当前文件所在目录的上上级目录）
BASE_DIR = Path(__file__).resolve().parent.parent
# 加载项目根目录下的.env文件，环境变量优先级：系统环境变量 > .env文件
# BASE_DIR = test_dj目录，需要向上一级到项目根目录
PROJECT_ROOT = BASE_DIR.parent
load_dotenv(PROJECT_ROOT / '.env')

# 2. 项目安全核心配置
# 项目秘钥，优先从.env读取，未读取到时使用默认值（仅开发环境）
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-@g2rhm)u#&zip#43#^mgdc$3&&l((8wrc-ti9nt!p0j6l87c#8')
# 调试模式，转换为布尔值，生产环境必须设置为False（安全警告）
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'
# 允许访问的主机列表，按逗号分割，默认值127.0.0.1和localhost
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') or ['127.0.0.1', 'localhost']

# 3. 已安装应用配置
INSTALLED_APPS = [
    # Django内置核心应用（后台管理、认证、会话等）
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方扩展应用（Django工具集）
    'django_extensions',
    # 项目自定义业务应用
    'app',
]

# 4. 中间件配置
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 5. URL根配置
# 项目主URL配置文件路径
ROOT_URLCONF = 'test_dj.urls'

# 6. 模板引擎配置
TEMPLATES = [
    {
        # 指定Django默认模板后端
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 全局模板文件目录（项目级模板）
        'DIRS': [BASE_DIR / 'templates'],
        # 启用应用内模板目录（app/templates）
        'APP_DIRS': True,
        # 模板上下文处理器（向所有模板传递公共变量）
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 7. WSGI应用配置
# 项目WSGI应用入口，用于生产环境服务器部署
WSGI_APPLICATION = 'test_dj.wsgi.application'

# 8. 数据库 & 自定义用户模型配置
# 指定项目自定义用户模型，替代Django默认User表（app应用下的User模型）
AUTH_USER_MODEL = 'app.User'
# 数据库连接配置，默认使用SQLite3（轻量文件型数据库）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # 数据库文件存储路径
    }
}

# 9. 密码验证规则配置
# 密码强度校验器，注册/修改密码时生效，按列表顺序校验
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 10. 国际化 & 本地化配置
USE_TZ = True  # 启用时区支持
TIME_ZONE = 'Asia/Shanghai'  # 项目使用时区（中国上海）
LANGUAGE_CODE = 'zh-hans'  # 项目默认语言（简体中文）
USE_I18N = True  # 启用国际化支持
USE_L10N = True  # 启用本地化支持（日期、数字等格式）

# 11. 静态文件配置（CSS/JS/图片等）
STATIC_URL = '/static/'  # 静态文件访问URL前缀
# 开发环境静态文件目录（指定项目内的静态文件路径，按原配置保留）
STATICFILES_DIRS = [BASE_DIR / "test_dj" / "static"]
# 生产环境静态文件收集目录（执行collectstatic命令时，所有静态文件会收集到该目录）
STATIC_ROOT = BASE_DIR / 'static_collect'

# 12. 媒体文件配置（用户上传文件）
MEDIA_URL = '/media/'  # 媒体文件访问URL前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 媒体文件本地存储根目录（含临时音频文件）
# 自动创建媒体目录，不存在则创建（递归创建父目录，忽略已存在）
if not MEDIA_ROOT.exists():
    MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

# 13. Django模型默认主键配置
# 所有模型未指定主键时，默认使用BigAutoField（大整数自增ID）
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 14. 邮件服务配置（敏感信息从.env读取）
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # SMTP邮件后端
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.qq.com')  # 邮件SMTP服务器地址
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))  # SMTP服务器端口，转换为整数（465=SSL, 587=TLS）
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '570510032@qq.com')  # 发件人邮箱
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # 邮箱授权码/密码，禁止明文
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'  # 启用SSL加密，转换为布尔值
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'  # 启用TLS加密，转换为布尔值
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 默认发件人邮箱（与发件人一致）

# 15. 阿里云AccessKey配置（ASR依赖，敏感信息）
# 阿里云访问密钥ID，优先从.env读取，禁止明文写死！
ALIYUN_ACCESS_KEY_ID = os.getenv('ALIYUN_ACCESS_KEY_ID', '')
# 阿里云访问密钥秘钥，优先从.env读取，禁止明文写死！
ALIYUN_ACCESS_KEY_SECRET = os.getenv('ALIYUN_ACCESS_KEY_SECRET', '')

# 16. 阿里云ASR语音识别核心配置
ALIYUN_ASR_CONFIG = {
    "endpoint": "nls-meta.cn-shanghai.aliyuncs.com",  # ASR服务地域端点
    "api_version": "2019-02-28",  # ASR接口API版本
    "model": "qwen3-asr-flash-realtime",  # 选用的语音识别模型（实时快识别）
    "format": "wav",  # 支持的音频文件格式
    "sample_rate": 16000,  # 音频采样率（16k Hz）
    "enable_punctuation_prediction": True,  # 开启识别结果的标点符号自动预测
}

# 17. 项目日志系统配置
LOGGING = {
    'version': 1,  # 日志配置版本（固定为1）
    'disable_existing_loggers': False,  # 不禁用现有日志器，兼容Django默认日志配置
    # 日志格式定义（输出内容、时间格式）
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',  # 日志时间戳格式
        },
    },
    # 日志处理器（日志输出方式：控制台/文件）
    'handlers': {
        # 控制台处理器（开发环境实时查看日志）
        'console': {
            'level': 'INFO',  # 输出级别：INFO及以上（INFO/WARNING/ERROR/CRITICAL）
            'class': 'logging.StreamHandler',
            'formatter': 'standard',  # 使用上面定义的standard格式
        },
        # 文件处理器（生产环境持久化保存，按大小切割）
        'file': {
            'level': 'INFO',  # 输出级别：INFO及以上
            'class': 'logging.handlers.RotatingFileHandler',  # 按文件大小切割的文件处理器
            'filename': BASE_DIR / 'logs' / 'test_dj.log',  # 日志文件存储路径
            'maxBytes': 1024 * 1024 * 10,  # 单个日志文件最大大小：10MB
            'backupCount': 10,  # 日志文件最大备份数：保留10个
            'formatter': 'standard',  # 使用standard格式
            'encoding': 'utf-8',  # 日志文件编码，避免中文乱码
        },
    },
    # 日志器配置（指定不同模块的日志处理方式）
    'loggers': {
        # 自定义服务：deepseek服务日志
        'app.services.deepseek_service': {
            'handlers': ['console', 'file'],  # 同时输出到控制台+文件
            'level': 'INFO',  # 日志级别
            'propagate': False,  # 不向上传递日志，避免重复输出
        },
        # 自定义服务：qwen3服务日志
        'app.services.qwen3_service': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django全局日志（保留，排查框架级问题）
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,  # 向上传递日志，兼容父日志器
        },
    },
}